template_path: templates/genie.yaml
stack_name: genie
dependencies:
  - essentials
  - sandcastlevpc
parameters:
  ComputeImageId: ami-283da057
  ContainerImage: sagebionetworks/genie:latest
  ContainerImage2: sagebionetworks/genie:vcf2maf
